package com.music.kevinmusic.enums;

public enum EventAction {
    SEARCH_SONG_BY_ID, SEARCH_SONG_BY_SINGLE_QUERY, SEARCH_SONG_ADVANCE, CREATE_SONG, UPDATE_SONG,
    DETAIL_PAGE, LANDING_PAGE, DOWNLOAD, COMMENT, REACTION,
    CREATE_USER, UPDATE_USER, SEARCH_USER_BY_ID, SEARCH_USER_BY_USERNAME, SEARCH_USER_ADVANCE
}
