package com.music.kevinmusic.domain;

public enum EventAction {
    SEARCH_SONG_BY_ID, SEARCH_SONG_BY_SINGLE_QUERY, SEARCH_SONG_ADVANCE,
    DETAIL_PAGE, LANDING_PAGE, DOWNLOAD,
    CREATE_USER, UPDATE_USER, SEARCH_USER_BY_ID, SEARCH_USER_BY_USERNAME, SEARCH_USER_ADVANCE
}
